const Single2026 = () => {
  return {
    content : <div>
      <h2>Bun gasit!</h2>
      <br />
      <p>A trecut si 2025 &hellip; mai grabit parca &hellip; pentru noi, mai intens, cu suisuri si coborasuri, care ne-au invatat ca rabdarea, linistea si calmul aduc decizii corecte &hellip; cand a contat felul in care-am crezut &hellip; daca am crezut ca putem, am putut, daca am crezut ca nu se poate, nu s-a putut &hellip;</p>
      <p>De cele mai multe ori am reusit, caci am ales credinta, credinta ca ceea ce facem este spre folosul celor de langa noi, a tinerilor cu sindrom Down care asteapta &ldquo;binele&rdquo; din partea noastra, <strong><em>Asociatia Prietenii D.A.R.I.E.I.</em></strong></p>
      <p>Si da! Acest lucru vi se datoreaza, caci ne-ati investit cu incredere, iar aceasta a fost sursa noastra de curaj, de a continua sa crestem, de la an la an, iata, depasind pragul deceniului de la infiintare.</p>
      <p>VA MULTUMIM!</p>
      <p>Si in 2025 tinerele noastre cu sindrom Down, Daria, Diana, Erin si Sara, au continuat sa faca pasi, din ce in ce mai siguri, spre sine si spre lume, pasi catre autonomia individuala, caci acesta este obiectivul <strong><em>Prietenilor D.A.R.I.E.I.</em></strong>: sa cladeasca drumul lor spre independenta personala.</p>
      <p>Permiteti-mi, va rog, sa mentionez principalele arii de implicare ale Asociatiei Prietenii D.A.R.I.E.I. in anul 2025:</p>
      <ul>
        <li><strong><em>cursuri de dezvoltare personala </em></strong>&ndash; prin metode de educatie nonformala, prin joc, improvizatie, muzica, teatru si poezie. Sedintele sunt coordonate de doamna Monica Lacramioara Lazarec, consilier de dezvoltare personala si formator. Incununarea efortului deosebit depus de doamna Monica Lazarec si de tinerele noastre care formeaza grupul &ldquo;Licuricii&rdquo;, va constitui punerea in scena a unei piese de teatru, in luna martie 2026. Piesa de teatru a fost scrisa special pentru tinerele &ldquo;Licurici&rdquo; de catre doamna Monica Lazarec si constinuie un prilej de descoperire si debarasare de frici pentru tinerele noastre speciale.</li>
        <li><strong><em>cursuri saptamanale de inot individuale</em></strong> (2025, pe parcursul anului), &ldquo;Complexul Olimpic de Natatie&rdquo;, Otopeni, instructor doamna Catalina, de la &ldquo;Euro Swimming Club&rdquo;, Bucuresti;</li>
        <li><strong><em>cursuri saptamanale de dansuri populare</em></strong> (2025, ianuarie &ndash; iunie 2025), &ldquo;Scoala de dans si muzica populara Bucuria&rdquo;, Bucuresti, instructor de dansuri populare - domnul Radu Savalache;</li>
        <li><strong><em>clase de zumba</em></strong> - incepand din septembrie 2025, <strong><em>Prietenii D.A.R.I.E.I.</em></strong> au imbratisat o noua provocare, cunoscand importanta miscarii fizice facuta cu placere: clase saptamanale de zumba cu instructor de dans, domnul Andrei Osanu, in locatia ZAR Complex, Bucuresti.</li>
        <li>De clasa de zumba s-au bucurat <strong><em>Prietenii D.A.R.I.E.I. </em></strong>si in data de 21.03.2025, la World Class Piata Sudului, la invitatia Special Olympics, pentru a marca Ziua Internationala a Sindromului Down.</li>
        <li><strong><em>cursuri de IT</em></strong> (2025, pe parcursul anului), organizate saptamanal de catre Asociatia &ldquo;Supereroilor&rdquo; - care dezvolta abilitati IT tinerilor cu dizabilitati, reprezentata de domnul Marius Braila, pentru toate lucrurile marete pe care le face in folosul persoanelor cu dizabilitati;</li>
        <li><strong><em>tabara de integrare si socializare</em></strong>, 01-05.09.2025, <strong><em>litoral romanesc</em></strong>, statiunea Saturn, hotel &ldquo;Sirena&rdquo;<strong><em>.</em></strong> Tinerii nostri frumosi au avut prilejul de a socializa, de a face miscare, de a dansa, de a lega noi relatii de prietenie, de a-si creste stima de sine;</li>
        <li><strong><em>activitati de socializare si recreere, vizionari de fime, spectacole, evenimente, </em></strong>pe parcursul anului 2025:</li>
        <li><strong><em>filme</em></strong>: 05.2025 - &ldquo;Sirenele II&rdquo;, cinema Hollywood Multiplex, 18.09.2025 - &ldquo;Baietii Rai II&rdquo;, cinema City, Bucuresti.</li>
        <li><strong><em>spectacole</em></strong>: 01.11.2025 &ndash; &ldquo;Doctorul Croitor&rdquo; &ndash; Teatrul Evreiesc, Bucuresti, pus in scena de catre doamna Monica Lazarec.</li>
        <li><strong><em>eveniment &ldquo;Targul Iepurasului&rdquo; </em></strong>- 16.04.2025, Centrul Scolar de Educatie Incluziva nr. 1, Bucuresti<strong><em>. </em></strong>Cu ocazia Sarbatorilor Pascale 2025, <strong><em>Prietenii D.A.R.I.E.I.</em></strong> au oferit daruri cu specific pascal tinerilor cu nevoi speciale, care invata in clasa a X a A, la Centrul Scolar de Educatie Incluziva nr. 1, Bucuresti, Aceste daruri constau in diverse seturi de creatie pascala, articole pentru desen oua de Paste, alte diverse articole de creatie cu specific pascal, cu ajutorul carora tinerii speciali mentionati contribuie la realizarea obiectelor traditionale pascale, pe care le-au prezentat la TARGUL IEPURASULUI, actiune organizata oe data de 16 aprilie 2025, intre orele 10:00-14:00, in incinta unitatii scolare mentionate.</li>
        <li><strong><em>eveniment - &ldquo;Mosul nu ne uita!&rdquo;, </em></strong>12.2025<strong><em> &ndash; </em></strong>eveniment dedicat sarbatorilor de iarna pentru tinerii cu nevoi speciale de la clasa a XI a A, Centrul Scolar de Educatie Incluziva nr. 1, sediul din Strada Traian 160, Bucuresti, care s-au bucurat de cadouri, dulciuri si decoratiuni specific de iarna, oferite de <strong><em>Prietenii D.A.R.I.E.I. </em></strong>De asemenea, tot cu</li>
        <li>aceasta ocazie, <strong><em>Asociatia</em></strong> a decorat scara interioara a cladirii, cu ghirlande de iarna, spre bucuria elevilor speciali si a cadrelor didactice din scoala.</li>
        <li><strong>eveniment -</strong><strong><em>&ldquo;Mosul iubeste Supereroii</em></strong>&rdquo;- 13.12.2025<strong><em>.</em></strong> La acest eveniment organizat de catre Asociatia &ldquo;Supereroilor&rdquo;, <strong><em>Asociatia Prietenii D.A.R.I.E.I. </em></strong>a pus la dispozitia tinerilor cu dizabilitati si voluntarilor lor inimosi, daruri constand in produse de cofetarie si patiserie.</li>
        <li><strong><em>eveniment - Ziua Internationala a Sindromului Down</em></strong>, marcata pe 27.03.2025, la Institutul National de Statistica, Bucuresti. Acest eveniment a fost organizat de catre Federatia Sindrom Down din Romania, Ministerul Muncii, Familiei, Tineretului si Solidaritatii Sociale si Autoritatea Nationala pentru protectia Drepturilor Persoanelor cu Dizabilitati.</li>
        <li><strong><em>Asociatia Prietenii D.A.R.I.E.I.</em></strong> a participat in calitate de membru al Federatiei Sindrom Down din Romania. Cu aceasta ocazie, am sustinut prezentarea cu titlul &ldquo;Ieri. Azi. Maine&rdquo;, in care am subliniat nevoile comunitatii tinerilor cu sindrom Down si insotitorilor acestora, nu doar din Bucuresti: consultanta in infiintarea de intreprinderi sociale, consultanta in atragerea de fonduri si granturi pentru proiecte sociale, programe special dezvoltate pentru a ajuta tinerii speciali sa faca fata tranzitiei catre viata adulta si vietii adulte. Tot cu aceasta ocazie, tinerele cu sindrom Down din Asociatie au prezentat un moment artistic - recitarea unei poezii dedicata zilei de 8 martie. Evenimentul s-a incheiat cu vizitarea Muzeului Cotroceni, de catre toti tinerii cu sindrom Down, din Bucuresti si din tara, prezenti la eveniment.</li>
        <li><strong><em>eveniment &ndash; Conferinta Nationala &ldquo;Inainte, pentru copiii Romaniei!&rdquo;</em></strong> &ndash; 14.04.2025, Biblioteca Nationala, Sala Mircea Eliade, Bucuresti. Acest eveniment a fost dedicat imbunatatirii accesibilitatii universale &ndash; accesibilitate academica si cea a spatiului public pentru tinerii cu dizabilitati, cu focus pe masuri concrete menite sa sprijine incluziunea sociala si mobilitatea<strong><em>. Asociatia</em></strong><strong><em>Prietenii D.A.R.I.E.I </em></strong>a fost prezenta la acest eveniment la invitatia conducerii Centrul Scolar de Educatie Incluziva nr. 1, evenimentul fiind organizat prin implicarea Primariei Sectorului 2 din Bucuresti.</li>
        <li><strong>eveniment &ndash; Biblioteca vie &ldquo;Democratia in actiune pentru o educatie incluziva&rdquo; </strong>&ndash; 4.06.2025, House of Europe, Bucuresti. <strong><em>Asociatia Prietenii D.A.R.I.E.I</em></strong><em>. </em>a fost prezenta la eveniment la invitatia Federatiei Sindrom Down din Romania. A fost prezentat conceptul de &ldquo;biblioteca vie&rdquo;, practic o persoana cu o abilitate speciala isi &ldquo;citeste&rdquo; celorlalti participanti, propria experienta. Este incurajator rezultatul experimentului, Acela ca tot mai multi tineri se implica direct in descoperirea sau constientizarea acestei comunitati a abilitatilor speciale, asa cum a fost redenumita dizabilitatea cu acest prilej.</li>
      </ul>
      <p>Acestia au fost &ldquo;Prietenii D.A.R.I.E.I.&rdquo; in 2025.</p>
      <p>Imagini surprinse la cele descrise mai sus, ca de altfel detalii despre intreaga noastra activitate, aflati pe <a href="https://asociatiaprieteniidariei.ro/">asociatiaprieteniidariei.ro</a></p>
      <p>Draga Prietene de ieri si de azi,</p>
      <p>Iti multumim pentru rabdare, timp si interes.</p>
      <p>De crezi in demersul nostru si doresti sa contribui, in mod absolut gratuit, la efortul sustinut de a imbunatati calitatea vietii tinerilor cu dizabilitati, cu sindrom Down in special, pe care Asociatia Prietenii D.A.R.I.E.I. ii sprijina, poti completa formularul 230 alaturat <strong>(CERERE PRIVIND DESTINATIA SUMEI REPREZENTAND PANA LA 3,5% DIN IMPOZITUL ANUAL DATORAT).</strong></p>
      <p>Acesta este precompletat cu datele Asociatiei Prietenii D.A.R.I.E.I., e nevoie doar sa treci datele tale si sa-l semnezi.</p>
      <p>Iti reamintim, aceasta este alegerea ta despre cum sa folosesti o parte din banii pe care i-ai virat deja statului, ca impozit pe venitul tau din anul 2025. Incepand din anul 2022, organizatiile non-profit pot depune formularele 230, in numele contribuabilului, exclusiv online. Prin completarea formularului 230 iti exprimi acordul ca <strong><em>Asociatia Prietenii D.A.R.I.E.I.</em></strong> sa prelucreze datele tale cu caracter personal, cu scopul inregistrarii acestuia on line, pe platforma e-guvernare, cu semnatura electronica autorizata.</p>
      <p>Fie ca alegi sa completezi on line formularul (cu Adobe Reader), fie ca-l printezi si-l trimiti scanat, il asteptam pe adresa <a href="mailto:prieteniidariei@gmail.com">prieteniidariei@gmail.com</a>, pana la data <strong>20.05.2026.</strong></p>
      <p>Un an mai bun, plin de experiente pe placul inimii!</p>
      <p>Cu prietenie,</p>
      <p>Ana si Daria Vasilescu,</p>
      <p><strong>Asociatia Prietenii D.A.R.I.E.I.</strong></p>
    </div>,
    yearId: 2026,
    desc: "Bun gasit!\n\nA trecut si 2025 ... mai grabit parca ... pentru noi, mai intens, cu suisuri si coborasuri, care ne-au invatat ca rabdarea, linistea si calmul aduc decizii corecte ... cand a contat felul in care-am crezut ... daca am crezut ca putem, am putut, daca am crezut ca nu se poate, nu s-a putut ... De cele mai multe ori am reusit, caci am ales credinta, credinta ca ceea ce facem este spre folosul celor de langa noi, a tinerilor cu sindrom Down care asteapta “binele” din partea noastra, Asociatia Prietenii D.A.R.I.E.I.",
  }
}

export default Single2026