
const Single2018 = () => {
  return {
    content:
      <div>
        <h2>Dragii nostri,</h2>
        <br />
        <p>Bine v-am regasit! Cu bucuria revederii unor Prieteni vechi, va imbratisez in gand si va transmit din suflet cat mai mult Bine, asa cum il intelege fiecare, in anul 2018!<br /> Prin sprijinul acordat anul trecut, completand formularul 230 pentru asociatia Prietenii D.A.R.I.E.I., ati facut posibila continuarea efortului nostru, inceput in urma cu 3 ani, de a ajuta sa evolueze copii cu dizabilitati, cu precadere copii cu Sindrom Down. Sa evolueze cognitiv, relational, social, emotional sau fizic.<br /> Privind-o pe Dariuca noastra, copil de 11 ani cu Sindrom Down, m-am intrebat nu de putine ori, de ce are ea nevoie cel mai mult? Ea si alti copii care ii "seamana". De suport financiar- a raspuns primul gand. Da, cu siguranta, datorita voua reusim "aici" si va multumim in numele acestor copii! De rabdare ... Sigur, cu carul!! Ce car! Cu camionul! Rabdarea asta insa pare a fi un fel de pasarea phoenix - rasare din propria noastra "ardere".<br /> De empatie si acceptare...o, Da, Da, Da!!! Cum sa zic &hellip; pasim pe taram arid, de multe ori...dar, continuam cautarile!</p>
        <p>Iata pe scurt cateva din implinirile anului 2017, datorate implicarii voastre:</p>
        <p>- Cu ocazia Zilei Internationale a Sindromului Down, 21 martie, asociatia Prietenii D.A.R.I.E.I. aachizitionat si a oferit kituri Montesori de invatare a scrisului, cititului si numeratiei - &rdquo;Descopar Literele&rdquo; si &rdquo;Descopar cifrele&rdquo; &ndash; copiilor din cadrul Centrului de zi Down al Complexului de Servicii Sociale &rdquo;Sfanta Ecaterina&rdquo; si a inca 4 copii cu certificat de handicap grav pe care asociatia noastra ii sprijina cu precadere;</p>
        <p>- Tot in luna martie 2017, am sustinut participarea catorva parinti de copii cu Sindrom Down la cursul &rdquo;Prevenirea si solutionarea tulburarilor de limbaj la copiii cu dizabilitati&rdquo;, organizat de 3 psihologi clinicieni cu experienta;</p>
        <p>- Cu ocazia zilei de 06 decembrie, asociatia a oferit pentru 20 copii cu cerinte educationale speciale din cadrul Scolii Speciale nr 8, Bucuresti pachete cu daruri de &rdquo; Mos Nicolae&rdquo;, primind cu bucurie spectacolul de sarbatori sustinut de ei;</p>
        <p>- &rdquo;Seara de aur a faptelor bune&rdquo; - sub aceasta denumire, in data de 14 decembrie, la Sala Ronda &ndash; Parcul Tei din Bucuresti, asociatia Prietenii D.A.R.I.E.I., alaturi de alte organizatii nonprofit participante, a bucurat 100 copii cu cerinte educationale speciale, cu varste cuprinse intre 2 si 12 ani, oferindu-le daruri de Craciun, respectiv carti cu tematica sarbatorilor de iarna - &rdquo;Mos Craciun si Ingerasii&rdquo; sau &rdquo;Activitati vesele de Craciun cu abtipilduri si felicitari&rdquo;;</p>
        <p>- In ziua de 16 decembrie, am oferit persoanelor gazduite in Centrul de Recuperare si Reabilitare Persoane cu Handicap Tancabesti, rucsacuri si pachete cu dulciuri, in cadrul unei actiuni care nu are cum sa nu te marcheze emotional si la care au participat voluntari inimosi;</p>
        <p>- Pe tot parcursul anului 2017, alaturi de Daria, inca o alta fetita cu Sindrom Down a putut sa continue sedintele terapeutice de logopedie si stimulare cognitiva, alaturi de sedintele de recuperare si intretinere fizica prin inot.</p>
        <p>In perioada urmatoare, dorim, alaturi de un psihoterapeut priceput, sa demaram o campanie de informare si constientizare a prezentei in scolile de masa a copiilor speciali, plecand de la propria noastra realitate intalnita in scoala la care Daria invata, dar si de la alte multe cazuri de care stim in jurul nostru. Lipsa empatiei - acesta este unul din principalele &rdquo;ziduri&rdquo; de care acesti copii se lovesc, atat din partea copiilor, dar si din partea parintilor lor si, uneori, chiar si a cadrelor didactice.</p>
        <p>Tot in acest sens, pe principiul &rdquo;unde-s multi puterea creste&rdquo; dorim sa reusim in 2018 sa aducem laolalta, intr-un cadru organizat, parinti si copii care se confrunta direct cu acest fel de a fi numit Sindrom Down, caci credem ca prin relatarea experientelor personale si exprimarea nevoilor putem genera si cai catre solutii posibile.</p>
        <p>Dar sa va spun si de abilitati, pentru ca da, si copiii cu Sindrom Down au abilitati!</p>
        <p>Caci este intr-adevar o mare calitate sa poti invata clipa de clipa pe cineva sa te iubeasca, daruindu-i permanent iubire neconditionata!</p>
        <p>Si asta face Daria! Ne preda neincetat lectia iubirii. De asta pot eu continua!</p>
        <p><br /> Daca si tu doresti sa continui sa sprijini demersul nostru, te rugam sa completezi formularul 230 alaturat (precompletat cu datele asociatiei).</p>
        <p>Il poti depune personal la sediul administratiei financiare de domiliciu, il poti expedia prin posta sau il poti depune online (dupa autentificare in Spatiul Privat Virtual - anaf .ro &ndash; o modalitate eficienta de a interactiona cu autorităţile fiscale online, de a cere si transmite diverse informaţii şi documente &icirc;ntr-un mod simplu şi eficient, din fata calculatorului).</p>
        <p>Asociatia Prietenii D.A.R.I.E.I. va incerca si in acest an sa vina in intampinarea ta, depunand formularul in numele tau, completand datele solicitate pe formular la sectiunea IV &rdquo;Imputernicit&rdquo;, in masura in care acest lucru va fi acceptat in continuare de catre administratiile financiare.</p>
        <p>Vom depune in doua etape, in prima etapa formularele pe care le vom avea pana in data de 1 martie 2018, iar ultima etapa de depunere va fi cel tarziu pana pe 25 mai 2018, data limita legala.</p>
        <p>Oricare ar fi modalitatea de expediere a formularului pe care o vei alege, te asiguram ca bucuria copiilor care primesc ceea ce le putem oferi impreuna, este cu adevarat greu de exprimat in cuvinte, iar imbratisarile lor sunt greu de uitat.</p>
        <p>Cu prietenie si respect,</p>
        <p>Ana Vasilescu si <strong>Asociatia Prietenii D.A.R.I.E.I.</strong></p>
      </div>,
    yearId: 2018,
    desc: 'Dragii nostri,\n\nBine v-am regasit! Cu bucuria revederii unor Prieteni vechi, va imbratisez in gand si va transmit din suflet cat mai mult Bine, asa cum il intelege fiecare, in anul 2018!<br /> Prin sprijinul acordat anul trecut, completand formularul 230 pentru asociatia Prietenii D.A.R.I.E.I., ati facut posibila continuarea efortului nostru, inceput in urma cu 3 ani, de a ajuta sa evolueze copii cu dizabilitati, cu precadere copii cu Sindrom Down. Sa evolueze cognitiv, relational, social, emotional sau fizic.<br /> Privind-o pe Dariuca noastra, copil de 11 ani cu Sindrom Down, m-am intrebat nu de putine ori, de ce are ea nevoie cel mai mult? Ea si alti copii care ii "seamana". De suport financiar- a raspuns primul gand. Da, cu siguranta, datorita voua reusim "aici" si va multumim in numele acestor copii! De rabdare ... Sigur, cu carul!! Ce car! Cu camionul! Rabdarea asta insa pare a fi un fel de pasarea phoenix - rasare din propria noastra "ardere".<br /> De empatie si acceptare...o, Da, Da, Da!!! Cum sa zic &hellip; pasim pe taram arid, de multe ori...dar, continuam cautarile! ',
  }
}

export default Single2018