const Single2025 = () => {
  return {
    content : <div>
      <h2><span>Trec anii, trec!</span></h2>
      <br />
      <p><span>In urma cu exact 10 ani infiintam&nbsp;</span><strong><em><span>Asociatia Prietenii D.A.R.I.E.I.</span></em></strong><span>&nbsp;cu credinta ca o putem ajuta pe Daria noastra si pe alte suflete frumoase asemeni ei, nascute cu Sindrom Down, sa-si afle locul lor sub soare, sa-si gaseasca rostul in societate, asa cum pot, in felul lor specific.&nbsp;</span></p>
      <p><span>Aveam sa aflam repede ca ajutorul este reciproc, multe avand sa invatam de la acesti copii, noi, parintii, sau alti &ldquo;oameni mari&rdquo;, care au avut si rabdarea, dar si determinarea sa-i cunoasca: am invatat ca iubirea se daruieste fara conditii, asa, pur si simplu, din inima, ca sa te bucuri apoi de ea, am invatat ca putem cultiva rabdarea, incepand cu noi insine, am invatat sa acceptam neuniformitatea, ca pe un normal existential, caci, nu-i asa?, nu am vrea sa fim cu totii identici &hellip; as mai putea continua, dar stiu cat de pretios este timpul.</span></p>
      <p><span>Timpul, inestimabila resursa a fiecaruia dintre noi!</span></p>
      <p><span>In 2024 Daria a implinit 18 ani, la fel ca si Diana, buna ei prietena. Normal ca s-au sarbatorit impreuna, alaturi de Erin (17 ani) si Sara (20 ani), celelalte doua bune prietene si colege de clasa.</span></p>
      <p><span>Si da, ne-am straduit sa le cream acestor tinere, dar nu numai, un mediu propice de dezvoltare, de aflare despre sine si despre lume, de invatare pasi spre independenta personala.</span></p>
      <p><span>Permiteti-mi, va rog, sa mentionez principalele arii de implicare ale Asociatiei Prietenii D.A.R.I.E.I. in anul 2024:</span></p>
      <ul>
        <li><p><strong><em><span>sedinte de dezvoltare personala</span></em></strong><span>&nbsp;(2024, incepand din martie)&ndash; prin metode de educatie nonformala, prin joc, improvizatie, muzica, teatru si poezie. Sedintele sunt coordonate de doamna Monica Lacramioara Lazarec, consilier de dezvoltare personala si formator, dureaza cate o ora si jumatate si se desfasora, si in prezent, de doua ori pe saptamana;&nbsp;</span></p></li>  
        <li><strong><em><span>sedinte saptamanale de inot</span></em></strong><span>, de grup/individuale (2024, pe parcursul anului), &ldquo;Complexul Olimpic de Natatie Otopeni&rdquo;, instructor doamna Catalina, de la &ldquo;Euro Swimming Club&rdquo;;</span></li>
        <li><strong><em><span>sedinte saptamanale de dansuri populare</span></em></strong><span>&nbsp;(2024, pe parcursul anului),&ldquo;Scoala de dans si muzica populara Bucuria&rdquo;, instructor de dansuri populare - domnul Radu Savalache;</span></li>
        <li><strong><em><span>cursuri de IT</span></em></strong><span>&nbsp;(2024, pe parcursul anului), organizate saptamanal de catre Asociatia &ldquo;Supereroilor&rdquo; - care &ldquo;dezvolta abilitati tinerilor cu dizabilitati&rdquo;, reprezentata de domnul Marius Braila, desemnat &ldquo;Omul Anului 2024&rdquo; pentru toate lucrurile marete pe care le face in folosul persoanelor cu dizabilitati;</span></li>
        <li><strong><em><span>tabara de integrare si socializare</span></em></strong><span>, 02-07.09.24,&nbsp;</span><strong><em><span>litoral romanesc</span></em></strong><span>, statiunea Saturn</span><strong><em><span>.</span></em></strong><span>&nbsp;Tinerii nostri frumosi au avut prilejul de a socializa, de a lega noi relatii de prietenie, de a-si creste stima de sine;&nbsp;</span></li>
        <li><strong><em><span>tabara de integrare si socializare</span></em></strong><span>, 11-13.10.24,&nbsp;</span><strong><em><span>munte</span></em></strong><span>, statiunea Busteni. Si Asociatia Prietenii D.A.R.I.E.I.</span><span>&nbsp;&nbsp;</span><span>a fost prezenta pe scena Centrului Cultural &ldquo;Aurel Stroe&rdquo; din Busteni cu un mic program artistic, alaturi de multe alte asociatii care fac parte din Federatia Sindrom Down din Romania;</span></li>
        <li><strong><em><span>Ziua Internationala a Sindromului Down</span></em></strong><span>, 21.03.24, Palatul Parlamentului. Asociatia Prietenii D.A.R.I.E.I. a participat ca invitat al Federatiei Sindrom Down din Romania, la Gala Sindrom Down;</span></li>
        <li><strong><em><span>Ziua Internationala a Dizabilitatii</span></em></strong><span>, 03.12.24, Palatului National al Copiilor. Asociatia Prietenii D.A.R.I.E.I. a oferit 30 pachete mini-instalatii luminoase, specifice sarbatorilor de iarna, tinerilor cu Sindrom Down care fac parte din Asociatia Down Plus Bucuresti si care au prezentat un spectacol incluziv de dansuri si voie buna, cu aceasta ocazie;</span></li>
        <li><strong><em><span>Business DisAbility Summit</span></em></strong><span>, 17.05.24, Palatul Parlamentului. &rsquo;&rsquo;Accesibilitatea si incluziunea redefinesc afacerile&rdquo; &ndash; sub aceasta deviza a fost organizat acest sumit, la care Asociatia Prietenii D.A.R.I.E.I. a fost prezenta;</span></li>
        <li><span>19-21.04-24, Braila. Asociatia Prietenii D.A.R.I.E.I. a fost invitata sa participe la Adunarea Generala a Asociatilor din cadrul Federatiei Sindrom Down din Romania, unde si-a manifestat dorinta de aderare la Federatie;</span></li>
        <li><span>04.09.24,&nbsp;</span><strong><em><span>Asociatia Prietenii D.A.R.I.E.I. este admisa oficial in Federatia Sindrom Down din Romania</span></em></strong><span>.</span></li>
        <li><span>Pe parcursul anului 2024: activitati de socializare si recreere, vizionari de fime, spectacole, evenimente:</span></li>
        <li><strong><em><span>filme</span></em></strong><span>:</span><span>&nbsp;&nbsp;</span><span>01.06.24 - &ldquo;Prieteni Imaginari&rdquo;, City Mall, 02.07.24 - &ldquo;Intors pe dos II&rdquo;, City Mall, 08.12.24 - &ldquo;Vaiana II&rdquo;, Hollywood Multiplex.</span></li>
        <li><strong><em><span>spectacole</span></em></strong><span>: 16.06.24 - spectacol pentru tineri cu dizabilitati, &ldquo;Inchide ochii si ai sa vezi mai bine&rdquo;, Teatrul de Comedie, 22.06.24 - spectacol &ldquo;Tribal&rdquo; sustinut de Corul de Copii Radio, Sala Radio, 06.11.24 - spectacol &ldquo;Delia&rdquo;, Beraria H, 22.12.24 - spectacol &ldquo;Raoul si Mirabela&rdquo;, Palatul National al Copiilor;</span></li>
        <li><span>10.03.24</span><strong><em><span>, eveniment Destiny Parc</span></em></strong><span>, Baneasa, parc de edutainment, in care tinerii nostri speciali au invatat, prin joaca, sa practice diverse meserii, fiind platiti cu bani magici pentru ele, experimentand autonomia si independenta;</span></li>
        <li><span>10.08.24,&nbsp;</span><strong><em><span>&rdquo;10 august, ziua noastra speciala</span></em></strong><span>&rdquo;: vizita la &ldquo;Muzeul Copiilor Sweet Adventure&rdquo;, cu atelier de gatit inclus, urmata de pinic in parc &ldquo;Herastrau&rdquo;, cu jocuri, miscare si socializare;</span></li>
        <li><span>24.10.24, petrecere &ldquo;</span><strong><em><span>Halloween&rdquo;</span></em></strong><span>, 6.12.24 -&nbsp;</span><strong><em><span>&ldquo;Mosul pe la noi&rdquo; &ndash;&nbsp;</span></em></strong><span>evenimente dedicate tinerilor cu nevoi speciale de la</span><strong><em><span>&nbsp;</span></em></strong><span>clasa a Xa A, Centrul Scolar de Educatie Incluziva nr. 1, Bucuresti, care s-au bucurat de cadouri, dulciuri si decoratiuni specifice</span><span>&nbsp;&nbsp;</span><span>oferite de Prietenii D.A.R.I.E.I.;</span></li>
        <li><span>14.12.24</span><span>,&nbsp;</span><span>eveniment&nbsp;</span><strong><em><span>&ldquo;Mosul la Supereroi&rdquo;.</span></em></strong><span>&nbsp;La acest eveniment organizat de catre Asociatia &ldquo;Supereroilor&rdquo;, Asociatia Prietenii D.A.R.I.E.I.a pus la dispozitia tinerilor cu dizabilitati prezenti aici daruri constand in produse de cofetarie si patiserie, sucuri si brelocuri tip suport telefon pentru tinerii voluntari implicati.</span></li>
        <li><span>21.12.24, eveniment&nbsp;</span><strong><em><span>&ldquo;Mosul de la Bowling&rdquo;</span></em></strong><span>. Tinerii speciali ai Asociatiei Prietenii D.A.R.I.E.I. au primit cadouri de la Federatia Romana de Bowling, cu ocazia sarbatorilor de iarna, eveniment organizat la IDM Club Bucuresti. Asociatia noastra intentioneaza sa dezvolte colaborarea cu Federatia Romana de Bowling in anul 2025.</span></li>
      </ul>
      <p><span>&nbsp;</span></p>
      <p><span>Acestia au fost &ldquo;Prietenii D.A.R.I.E.I.&rdquo; in 2024.</span></p>
      <p><span>Imagini de la momentele descrise mai sus, ca de altfel detalii despre intreaga noastra activitate pe parcursul a celor 10 ani de la infiintare, gasiti pe&nbsp;</span><a href="https://asociatiaprieteniidariei.ro/"><span>asociatiaprieteniidariei.ro</span></a><span>&nbsp;</span></p>
      <p><span>Acest site este realizat integral de Cosmin, fratele Dariei.&nbsp;</span></p>
      <p><span>A fost cadoul lui, la majoratul ei.</span></p>
      <p><span>&nbsp;</span></p>
      <p><span>Draga Prietene de ieri si de azi,</span></p>
      <p><span>Iti multumim pentru rabdare, timp si interes.&nbsp;</span></p>
      <p><span>De crezi in demersul nostru si doresti sa contribui, in mod absolut gratuit, la efortul sustinut de a imbunatati calitatea vietii tinerilor cu dizabilitati, cu Sindrom Down in special, pe care Asociatia Prietenii D.A.R.I.E.I. ii sprijina, poti completa formularul 230 anexat&nbsp;</span><strong><span>(CERERE PRIVIND DESTINATIA SUMEI REPREZENTAND PANA LA 3,5% DIN IMPOZITUL ANUAL DATORAT)</span></strong></p>
      <p><span>Iti reamintim, aceasta nu este o donatie, este doar alegerea ta despre cum sa folosesti o parte din banii pe care i-ai virat deja statului, ca impozit pe venitul tau din anul 2024. Incepand din anul 2022, organizatiile non-profit pot depune formularele 230, in numele contribuabilului, exclusiv online. Prin completarea formularului 230 iti exprimi acordul ca sa prelucreze datele tale cu caracter personal, cu scopul inregistrarii acestuia on line, pe platforma e-guvernare, cu semnatura electronica autorizata.</span></p>
      <p><span>Fie ca alegi sa completezi on line formularul (cu Adobe Reader), fie ca-l printezi si-l trimiti scanat, il asteptam pe adresa&nbsp;</span><a href="mailto:prieteniidariei@gmail.com"><span>prieteniidariei@gmail.com</span></a><span>, pana la data&nbsp;</span><strong><span>20.05.2025.</span></strong></p>
      <p><span>Apreciaza fiecare zi!</span></p>
      <p><span>Cu prietenie,&nbsp;</span></p>
      <p><span>Ana si Daria Vasilescu,&nbsp;</span></p>
      <p><span>Asociatia Prietenii D.A.R.I.E.I.</span></p>
    </div>,
    yearId: 2025,
    desc: "Trec anii, trec!\n\nIn urma cu exact 10 ani infiintam Asociatia Prietenii D.A.R.I.E.I. cu credinta ca o putem ajuta pe Daria noastra si pe alte suflete frumoase asemeni ei, nascute cu Sindrom Down, sa-si afle locul lor sub soare, sa-si gaseasca rostul in societate, asa cum pot, in felul lor specific. Aveam sa aflam repede ca ajutorul este reciproc, multe avand sa invatam de la acesti copii, noi,",
  }
}

export default Single2025